# Generated by Django 4.1.5 on 2023-09-30 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('subject', models.CharField(max_length=40)),
                ('description', models.TextField()),
                ('Links', models.TextField()),
                ('date_created', models.DateField(auto_now_add=True, null=True)),
                ('rate', models.PositiveSmallIntegerField(default=0)),
                ('rated', models.TextField(default='p')),
                ('author', models.CharField(max_length=50)),
            ],
        ),
    ]
